.github/workflows/continous-integration-workflow.yaml

APM-1645 master >> main

---

.gitignore
Makefile
azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
ecs-proxies-containers.yml
ecs-proxies-deploy-sandbox.yml

apm-1351: aws build agents temporary pinned utils

---

Makefile
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/e2e.yml
e2e/Makefile
e2e/tests/api_tests.py

apm-1351: support separate e2e/smoketest execution

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

apm-1351: set back to master branch

---

Makefile

Update `make release` to deploy to prod also

APM-1598 Deploy ECS to prod also

---

azure/azure-pr-pipeline.yml
e2e/pyproject.toml
e2e/tests/api_tests.py

change tests to use allow_retries

APM-1710 change tests to allow retries

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
docker/app.js
manifest_template.yml
proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
proxies/live/apiproxy/policies/VerifyApiKey-Header.xml
proxies/live/apiproxy/proxies/default.xml

apm-1556: add log to splunk callout to canary

---

azure/azure-release-pipeline.yml

APM-1162 Fix tests for prod

---

manifest_template.yml

-------
Add the new style scopes to the manifest_template

APM-1701 Add new scopes to manifest_template

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
poetry.toml

No need to merge. Just testing utils changes

APM-1746 integrate s3 cache action with utils

---

azure/azure-build-pipeline.yml

APM-2016 Temp fix caching

---

azure/azure-release-pipeline.yml

* Add short name to extra stage

Apm 2016 enable monitoring add stage

---

azure/templates/e2e.yml
e2e/pyproject.toml
e2e/tests/api_tests.py
package-lock.json
proxies/live/apiproxy/policies/KeyValueMapOperations.GetSharedSecureVariables.xml
proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
proxies/live/apiproxy/policies/VerifyApiKey-Header.xml
proxies/live/apiproxy/proxies/default.xml

APM-2231 Fix status flow by checking apikey from secure variables

---

docker/app.js

APM-2234 Add status to response

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

For testing enable_status_monitoring flag

AMB-536 Point to utils PR for release monitoring testing

---

azure/azure-build-pipeline.yml

AMB-536 point build to utils pr for testing

---

azure/azure-release-pipeline.yml

AMB-536 enable status monitoring by default

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

AMB-536 Point to utils master branch

---

azure/azure-release-pipeline.yml

AMB-783 Deleted monitoring flags, default set to true

---

.gitignore
proxies/live/apiproxy/policies/AssignMessage.QuotaData.xml
proxies/live/apiproxy/policies/AssignMessage.QuotaPerAppErrorMessage.xml
proxies/live/apiproxy/policies/AssignMessage.QuotaPerProxyErrorMessage.xml
proxies/live/apiproxy/policies/Javascript.SetQuotaVars.xml
proxies/live/apiproxy/policies/Quota.xml
proxies/live/apiproxy/policies/QuotaPerApp.xml
proxies/live/apiproxy/policies/QuotaPerProxy.xml
proxies/live/apiproxy/proxies/default.xml
proxies/live/apiproxy/resources/jsc/set-quota-vars.js
proxies/live/apiproxy/targets/canary-target.xml

This is a work in progress, using PR deployments to test various things.

Per-app rate limiting

---

README.md
azure/azure-release-pipeline.yml

Reverts NHSDigital/canary-api#72

Revert "AMB-783 created another pr to check for 503 on initial pr"

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

APM-2016 Point at edge

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

APM-2016 Revert back to utils master

---

azure/azure-build-pipeline.yml

Reverts NHSDigital/canary-api#83

Revert "APM-2348 Build the right utils"

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

Reverts NHSDigital/canary-api#82

Revert "APM-2348 Point to saml-ified pipeline"

---

azure/azure-release-pipeline.yml
manifest_template.yml

Revert changes made to make visible in portal back to non-visible

APM-2530 Revert canary

---

azure/azure-build-pipeline.yml

APM-2016 Disable caching

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

APM-2016 Add caching back in

---

.github/workflows/continous-integration-workflow.yaml

Disable unnecessary build steps on GitHub workflows.

APM-000 Disable unnecessary build steps on github

---

.github/workflows/continous-integration-workflow.yaml

APM-000 change branch name

---

.github/workflows/continous-integration-workflow.yaml

APM-000 fix release workflow

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

testing producer manual approval for prod...

APM-2321 point to utils pr

---

azure/azure-release-pipeline.yml

APM-2321 disable producer approval

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

APM-2321 test producer manual approval for prod

---

manifest_template.yml

APM-3095 Add mock identity service

---

manifest_template.yml

APM-3430 Add nhs-login scope to canary

---

proxies/live/apiproxy/proxies/default.xml

Added endpoint protected by API key to be used by Proxygen integration tests.

APM-3406 add endpoint for proxygen external backend integration tests

---

proxies/live/apiproxy/policies/AssignMessage.MagicResponse.xml
proxies/live/apiproxy/proxies/default.xml

Add payload to proxygen testing endpoint

APM-3406 add payload to endpoint response

---

manifest_template.yml

APM-3740 Add dep identity service capability for dev

---

package-lock.json
package.json

remove newman

---

manifest_template.yml

APM-3686 configure mock auth for new envs

---

manifest_template.yml
specification/canary-api.yaml

apm-4807 temporarily add a product to test change to common pipelines

---

docker/package-lock.json
package-lock.json

Apm 5386 update version

---

azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

APM-5855 Use the main pool for canary

---

azure/azure-release-pipeline.yml
manifest_template.yml

APM-6519 fix for Dev --> Dep
